[firebase]

apiKey = "AIzaSyBeF5OCJiNtEmUCPS2HZt98qAD3B-0Sw5g"
authDomain = "mywebapp1-f7464.firebaseapp.com"
projectId = "mywebapp1-f7464"
storageBucket = "mywebapp1-f7464.firebasestorage.app"
messagingSenderId = "609729595021"
appId = "1:609729595021:web:b5e9f42ccba96c1c29c4c4"
measurementId = "G-QKN5TE2J4J"
databaseURL = "https://mywebapp1-f7464-default-rtdb.firebaseio.com/"
